name: "Laravel 8"
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                laravel: [ "8.0" ]
                php: [ "8.0", "8.1" ]

        name: PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup Redis
                uses: zhulik/redis-action@1.1.0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis
                    coverage: none

            -   name: Install dependencies
                run: composer require --dev laravel/framework:^${{ matrix.laravel }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
