name: phpunit
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.3", "7.4", "8.0" ]
                laravel: [ "6.0", "7.0", "8.0" ]

        name: php ${{ matrix.php }}, l ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup Redis
                uses: zhulik/redis-action@1.1.0

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis
                    coverage: none

            -   name: Install dependencies
                run: composer require --dev laravel/framework:^${{ matrix.laravel }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
